package com.weixin.web.entity.message;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

// Generated 2014-8-18 9:58:30 by Hibernate Tools 3.2.2.GA

/**
 * WxArticle generated by hbm2java
 */
@Entity
@Table(name = "wx_article")
public class WxArticle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "ID", nullable = false, length = 36)
	private String id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name="WX_MASS_ID")
	private WxMass wxMass;
	
	@Column(name = "thumb_media_id")
	private String thumbMediaId;
	
	@Column(name = "thumb_media_url")
	private String thumbMediaUrl;
	
	@Column(name = "author")
	private String author;
	
	@Column(name = "title")
	private String title;
	
	@Column(name = "content_source_url")
	private String contentSourceUrl;
	
	@Column(name = "content")
	private String content;
	
	@Column(name = "digest")
	private String digest;
	
	@Column(name = "show_cover_pic")
	private String showCoverPic;
	
	@Column(name = "sort")
	private Integer sort;
	
	@Column(name = "addTime")
	private String addTime;
	
	

	public WxArticle() {
	}

	public WxArticle(String id) {
		this.id = id;
	}

	public WxArticle(String id, WxMass wxMass, String thumbMediaId,
			String thumbMediaUrl, String author, String title,
			String contentSourceUrl, String content, String digest,
			String showCoverPic, Integer sort, String addTime) {
		this.id = id;
		this.wxMass = wxMass;
		this.thumbMediaId = thumbMediaId;
		this.thumbMediaUrl = thumbMediaUrl;
		this.author = author;
		this.title = title;
		this.contentSourceUrl = contentSourceUrl;
		this.content = content;
		this.digest = digest;
		this.showCoverPic = showCoverPic;
		this.sort = sort;
		this.addTime = addTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public WxMass getWxMass() {
		return this.wxMass;
	}

	public void setWxMass(WxMass wxMass) {
		this.wxMass = wxMass;
	}

	public String getThumbMediaId() {
		return this.thumbMediaId;
	}

	public void setThumbMediaId(String thumbMediaId) {
		this.thumbMediaId = thumbMediaId;
	}

	public String getThumbMediaUrl() {
		return this.thumbMediaUrl;
	}

	public void setThumbMediaUrl(String thumbMediaUrl) {
		this.thumbMediaUrl = thumbMediaUrl;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContentSourceUrl() {
		return this.contentSourceUrl;
	}

	public void setContentSourceUrl(String contentSourceUrl) {
		this.contentSourceUrl = contentSourceUrl;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getDigest() {
		return this.digest;
	}

	public void setDigest(String digest) {
		this.digest = digest;
	}

	public String getShowCoverPic() {
		return this.showCoverPic;
	}

	public void setShowCoverPic(String showCoverPic) {
		this.showCoverPic = showCoverPic;
	}

	public Integer getSort() {
		return sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getAddTime() {
		return addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

	
}
