package com.weixin.web.entity.message;

// Generated 2014-8-18 9:58:30 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WxMass generated by hbm2java
 */
@Entity
@Table(name = "wx_mass")
public class WxMass implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "ID", nullable = false, length = 36)
	private String id;
	
	@Column(name = "massName")
	private String massName;
	
	@Column(name = "send")
	private String send;
	
	@Column(name = "msgid")
	private Integer msgid;
	
	@Column(name = "addTime")
	private String addTime;
	
	@Column(name = "accountId")
	private String accountId;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wxMass" )
	private Set<WxArticle> wxArticles = new HashSet<WxArticle>(0);

	public WxMass() {
	}

	public WxMass(String id) {
		this.id = id;
	}

	public WxMass(String id, String massName, String send, Integer msgid, String addTime,
			String accountId, Set<WxArticle> wxArticles) {
		this.id = id;
		this.massName = massName;
		this.send = send;
		this.addTime = addTime;
		this.accountId = accountId;
		this.wxArticles = wxArticles;
		this.msgid = msgid;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMassName() {
		return this.massName;
	}

	public void setMassName(String massName) {
		this.massName = massName;
	}

	public String getSend() {
		return this.send;
	}

	public void setSend(String send) {
		this.send = send;
	}
	
	public Integer getMsgid() {
		return msgid;
	}

	public void setMsgid(Integer msgid) {
		this.msgid = msgid;
	}

	public String getAddTime() {
		return this.addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public Set<WxArticle> getWxArticles() {
		return this.wxArticles;
	}

	public void setWxArticles(Set<WxArticle> wxArticles) {
		this.wxArticles = wxArticles;
	}

}
