package com.weixin.web.entity.message;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2014-8-7 14:54:17 by Hibernate Tools 3.2.2.GA

/**
 * WxNewsitem generated by hbm2java
 */
@Entity
@Table(name = "wx_newsitem")
public class WxNewsitem implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID", nullable = false, length = 36)
	private String id;
	
	@Column(name = "title")
	private String title;
	
	@Column(name = "author")
	private String author;
	
	@Column(name = "description")
	private String description;
	
	@Column(name = "content")
	private String content;
	
	@Column(name = "picUrl")
	private String picUrl;
	
	@Column(name = "url")
	private String url;
	
	@Column(name = "sort")
	private String sort;
	
	@Column(name = "templateId")
	private String templateId;
	
	@Column(name = "accountId")
	private String accountId;
	
	@Column(name = "addTime")
	private String addTime;

	public WxNewsitem() {
	}

	public WxNewsitem(String id) {
		this.id = id;
	}

	public WxNewsitem(String id, String title, String description,
			String picUrl, String url, String templateId, String accountId, String author,
			String content, String sort, String addTime) {
		this.id = id;
		this.title = title;
		this.author = author;
		this.description = description;
		this.content = content;
		this.picUrl = picUrl;
		this.url = url;
		this.templateId = templateId;
		this.accountId = accountId;
		this.sort = sort;
		this.addTime = addTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	
	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getPicUrl() {
		return this.picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(String templateId) {
		this.templateId = templateId;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getSort() {
		return sort;
	}

	public void setSort(String sort) {
		this.sort = sort;
	}

	public String getAddTime() {
		return addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

	
}
