package com.weixin.web.entity.message;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2014-8-7 14:54:17 by Hibernate Tools 3.2.2.GA

/**
 * WxTexttemplate generated by hbm2java
 */
@Entity
@Table(name = "wx_texttemplate")
public class WxTexttemplate implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID", nullable = false, length = 36)
	private String id;

	@Column(name = "addTime")
	private String addTime;

	@Column(name = "templateName")
	private String templateName;

	@Column(name = "content")
	private String content;

	@Column(name = "accountId")
	private String accountId;

	public WxTexttemplate() {
	}

	public WxTexttemplate(String id) {
		this.id = id;
	}

	public WxTexttemplate(String id, String addTime, String templateName,
			String content, String accountId) {
		this.id = id;
		this.addTime = addTime;
		this.templateName = templateName;
		this.content = content;
		this.accountId = accountId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAddTime() {
		return this.addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

}
