package org.weixin.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2014-8-7 10:34:10 by Hibernate Tools 3.2.2.GA

/**
 * WxEvent generated by hbm2java
 */
@Entity
@Table(name = "wx_event")
public class WxEvent implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "ID", nullable = false, length = 36)
	private String id;
	
	@Column(name = "accountId")
	private String accountId;
	
	@Column(name = "FromUserName")
	private String fromUserName;
	
	@Column(name = "ToUserName")
	private String toUserName;
	
	@Column(name = "CreateTime")
	private String createTime;
	
	@Column(name = "MsgType")
	private String msgType;
	
	@Column(name = "event")
	private String event;
	
	@Column(name = "eventKey")
	private String eventKey;
	
	@Column(name = "ticket")
	private String ticket;
	
	@Column(name = "latitude")
	private String latitude;
	
	@Column(name = "longitude")
	private String longitude;
	
	@Column(name = "pprecision")
	private String pprecision;

	
	public WxEvent() {
	}

	public WxEvent(String id) {
		this.id = id;
	}

	public WxEvent(String id, String accountId, String fromUserName,
			String toUserName, String createTime, String msgType, String event,
			String eventKey, String ticket, String latitude, String longitude,
			String pprecision) {
		this.id = id;
		this.accountId = accountId;
		this.fromUserName = fromUserName;
		this.toUserName = toUserName;
		this.createTime = createTime;
		this.msgType = msgType;
		this.event = event;
		this.eventKey = eventKey;
		this.ticket = ticket;
		this.latitude = latitude;
		this.longitude = longitude;
		this.pprecision = pprecision;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getFromUserName() {
		return this.fromUserName;
	}

	public void setFromUserName(String fromUserName) {
		this.fromUserName = fromUserName;
	}

	public String getToUserName() {
		return this.toUserName;
	}

	public void setToUserName(String toUserName) {
		this.toUserName = toUserName;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getMsgType() {
		return this.msgType;
	}

	public void setMsgType(String msgType) {
		this.msgType = msgType;
	}

	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	public String getEventKey() {
		return this.eventKey;
	}

	public void setEventKey(String eventKey) {
		this.eventKey = eventKey;
	}

	public String getTicket() {
		return this.ticket;
	}

	public void setTicket(String ticket) {
		this.ticket = ticket;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getPprecision() {
		return this.pprecision;
	}

	public void setPprecision(String pprecision) {
		this.pprecision = pprecision;
	}

}
