package org.weixin.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2014-8-15 10:52:17 by Hibernate Tools 3.2.2.GA

/**
 * WxGroup generated by hbm2java
 */
@Entity
@Table(name = "wx_group")
public class WxGroup implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "ID", nullable = false, length = 36)
	private String id;
	
	@Column(name = "name")
	private String name;
	
	@Column(name = "groupId")
	private String groupId;
	
	@Column(name = "count")
	private String count;
	
	@Column(name = "accountid")
	private String accountid;
	
	@Column(name = "addTime")
	private String addTime;
	
	@Column(name = "modifyTime")
	private String modifyTime;

	public WxGroup() {
	}

	public WxGroup(String id) {
		this.id = id;
	}

	public WxGroup(String id, String name, String groupId,String count, String accountid,
			String addTime, String modifyTime) {
		this.id = id;
		this.name = name;
		this.groupId = groupId;
		this.count = count;
		this.accountid = accountid;
		this.addTime = addTime;
		this.modifyTime = modifyTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGroupId() {
		return groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	public String getCount() {
		return this.count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	public String getAccountid() {
		return this.accountid;
	}

	public void setAccountid(String accountid) {
		this.accountid = accountid;
	}

	public String getAddTime() {
		return addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

	public String getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

}
