package org.weixin.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2014-8-15 10:52:17 by Hibernate Tools 3.2.2.GA

/**
 * WxUserinfo generated by hbm2java
 */
@Entity
@Table(name = "wx_userinfo")
public class WxUserinfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "ID", nullable = false, length = 36)
	private String id;
	
	@Column(name = "subscribe")
	private String subscribe;
	
	@Column(name = "openid")
	private String openid;
	
	@Column(name = "nickname")
	private String nickname;
	
	@Column(name = "sex")
	private Integer sex;
	
	@Column(name = "city")
	private String city;
	
	@Column(name = "country")
	private String country;
	
	@Column(name = "province")
	private String province;
	
	@Column(name = "language")
	private String language;
	
	@Column(name = "headimgurl")
	private String headimgurl;
	
	@Column(name = "subscribe_time")
	private String subscribeTime;
	
	@Column(name = "unionid")
	private String unionid;
	
	@Column(name = "remark")
	private String remark;
	
	@Column(name = "accountid")
	private String accountid;
	
	@Column(name = "tag")
	private String tag;

	public WxUserinfo() {
	}

	public WxUserinfo(String id) {
		this.id = id;
	}

	public WxUserinfo(String id, String subscribe, String openid,
			String nickname, Integer sex, String city, String country,
			String province, String language, String headimgurl,
			String subscribeTime, String unionid, String remark,
			String accountid, String tag) {
		this.id = id;
		this.subscribe = subscribe;
		this.openid = openid;
		this.nickname = nickname;
		this.sex = sex;
		this.city = city;
		this.country = country;
		this.province = province;
		this.language = language;
		this.headimgurl = headimgurl;
		this.subscribeTime = subscribeTime;
		this.unionid = unionid;
		this.remark = remark;
		this.accountid = accountid;
		this.tag = tag;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSubscribe() {
		return this.subscribe;
	}

	public void setSubscribe(String subscribe) {
		this.subscribe = subscribe;
	}

	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getHeadimgurl() {
		return this.headimgurl;
	}

	public void setHeadimgurl(String headimgurl) {
		this.headimgurl = headimgurl;
	}

	public String getSubscribeTime() {
		return this.subscribeTime;
	}

	public void setSubscribeTime(String subscribeTime) {
		this.subscribeTime = subscribeTime;
	}

	public String getUnionid() {
		return this.unionid;
	}

	public void setUnionid(String unionid) {
		this.unionid = unionid;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getAccountid() {
		return this.accountid;
	}

	public void setAccountid(String accountid) {
		this.accountid = accountid;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

}
