package com.weixin.web.entity;
// Generated 2014-7-3 15:55:50 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Articlesapply generated by hbm2java
 */
@Entity
@Table(name = "articlesapply")
public class Articlesapply implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID", nullable = false, length = 36)
	private String id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "STATUSID")//不能有unique = true
	private Currentstatus currentstatus;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MSGID", unique = true)
	private Message message;
	
	@Column(name = "APPLYUSER")
	private String applyUser;
	
	@Column(name = "APPLYREASON")
	private String applyReason;
	
	@Column(name = "APPLYTIME")
	private String applyTime;
	
	@Column(name = "OWNER")
	private String owner;
	
	@Column(name = "REMARK")
	private String remark;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "articlesapply")
	private Set<Applyarticlesversion> applyarticlesversions = new HashSet<Applyarticlesversion>(0);

	public Articlesapply() {
	}

	public Articlesapply(String id) {
		this.id = id;
	}

	public Articlesapply(String id, Currentstatus currentstatus,
			Message message, String applyUser, String applyReason,
			String applyTime, String owner, String remark,
			Set<Applyarticlesversion> applyarticlesversions) {
		this.id = id;
		this.currentstatus = currentstatus;
		this.message = message;
		this.applyUser = applyUser;
		this.applyReason = applyReason;
		this.applyTime = applyTime;
		this.owner = owner;
		this.remark = remark;
		this.applyarticlesversions = applyarticlesversions;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Currentstatus getCurrentstatus() {
		return this.currentstatus;
	}

	public void setCurrentstatus(Currentstatus currentstatus) {
		this.currentstatus = currentstatus;
	}

	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	public String getApplyUser() {
		return this.applyUser;
	}

	public void setApplyUser(String applyUser) {
		this.applyUser = applyUser;
	}

	public String getApplyReason() {
		return this.applyReason;
	}

	public void setApplyReason(String applyReason) {
		this.applyReason = applyReason;
	}

	public String getApplyTime() {
		return this.applyTime;
	}

	public void setApplyTime(String applyTime) {
		this.applyTime = applyTime;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<Applyarticlesversion> getApplyarticlesversions() {
		return this.applyarticlesversions;
	}

	public void setApplyarticlesversions(Set<Applyarticlesversion> applyarticlesversions) {
		this.applyarticlesversions = applyarticlesversions;
	}

}
