package com.weixin.web.entity;
// Generated 2014-7-3 15:55:50 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Currentstatus generated by hbm2java
 */
@Entity
@Table(name = "currentstatus")
public class Currentstatus implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "ID", nullable = false)
	private int id;
	
	@Column(name = "CURRENTSTATUS")
	private String currentStatus;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "currentstatus")
	private Set<Articlesapply> articlesapplies = new HashSet<Articlesapply>(0);

	public Currentstatus() {
	}

	public Currentstatus(int id) {
		this.id = id;
	}

	public Currentstatus(int id, String currentStatus, Set<Articlesapply> articlesapplies) {
		this.id = id;
		this.currentStatus = currentStatus;
		this.articlesapplies = articlesapplies;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCurrentStatus() {
		return this.currentStatus;
	}

	public void setCurrentStatus(String currentStatus) {
		this.currentStatus = currentStatus;
	}

	public Set<Articlesapply> getArticlesapplies() {
		return this.articlesapplies;
	}

	public void setArticlesapplies(Set<Articlesapply> articlesapplies) {
		this.articlesapplies = articlesapplies;
	}

}
