package com.weixin.web.entity;

// Generated 2014-7-3 15:55:50 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message")
public class Message implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "ID", nullable = false, length = 36)
	private String id;
	
	@Column(name = "CREATETIME")
	private String createTime;
	
	@Column(name = "MSGTYPE")
	private String msgType;
	
	@Column(name = "CONTENT")
	private String content;
	
	@Column(name = "PICURL")
	private String picUrl;
	
	@Column(name = "TITLE")
	private String title;
	
	@Column(name = "DESCRIPTION")
	private String description;
	
	@Column(name = "URL")
	private String url;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "message")
	private Set<Articlesapply> articlesapplies = new HashSet<Articlesapply>(0);

	public Message() {
	}

	public Message(String id) {
		this.id = id;
	}

	public Message(String id, String createTime, String msgType,
			String content, String picUrl, String title, String description,
			String url, Set<Articlesapply> articlesapplies) {
		this.id = id;
		this.createTime = createTime;
		this.msgType = msgType;
		this.content = content;
		this.picUrl = picUrl;
		this.title = title;
		this.description = description;
		this.url = url;
		this.articlesapplies = articlesapplies;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getMsgType() {
		return this.msgType;
	}

	public void setMsgType(String msgType) {
		this.msgType = msgType;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getPicUrl() {
		return this.picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Set<Articlesapply> getArticlesapplies() {
		return this.articlesapplies;
	}

	public void setArticlesapplies(Set<Articlesapply> articlesapplies) {
		this.articlesapplies = articlesapplies;
	}

}
