package com.weixin.web.entity;

// Generated 2014-6-27 15:52:44 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tprivilege generated by hbm2java
 */
@Entity
@Table(name = "tprivilege")
public class Tprivilege implements java.io.Serializable {

	@Id
	@Column(name = "ID", nullable = false, length = 36)
	private String id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pid")
	private Tprivilege tprivilege;
	
	@Column(name = "NAME")
	private String name;
	
	@Column(name = "URL")
	private String url;
	
	@Column(name = "CREATETIME")
	private String createTime;
	
	@Column(name = "ISCANCEL")
	private String isCancel;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tprivilege", targetEntity = TrolePrivilege.class)
	private Set trolePrivileges = new HashSet(0);

	public Tprivilege() {
	}

	public Tprivilege(String id) {
		this.id = id;
	}

	public Tprivilege(String id, Tprivilege tprivilege, String name, String url, String createTime,
			String isCancel, Set trolePrivileges) {
		this.id = id;
		this.tprivilege = tprivilege;
		this.name = name;
		this.url = url;
		this.createTime = createTime;
		this.isCancel = isCancel;
		this.trolePrivileges = trolePrivileges;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	public Tprivilege getTprivilege() {
		return tprivilege;
	}

	public void setTprivilege(Tprivilege tprivilege) {
		this.tprivilege = tprivilege;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getIsCancel() {
		return this.isCancel;
	}

	public void setIsCancel(String isCancel) {
		this.isCancel = isCancel;
	}

	public Set getTrolePrivileges() {
		return this.trolePrivileges;
	}

	public void setTrolePrivileges(Set trolePrivileges) {
		this.trolePrivileges = trolePrivileges;
	}

}
