package com.weixin.web.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
// Generated 2014-6-27 15:52:44 by Hibernate Tools 3.2.2.GA
import javax.persistence.Table;

/**
 * TrolePrivilege generated by hbm2java
 */
@Entity
@Table(name = "trole_privilege")
public class TrolePrivilege implements java.io.Serializable {

	@Id
	@Column(name = "ID", nullable = false, length = 36)
	private String id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name="ROLEID")
	private Trole trole;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name="PRIVILEGEID")
	private Tprivilege tprivilege;

	public TrolePrivilege() {
	}

	public TrolePrivilege(String id) {
		this.id = id;
	}

	public TrolePrivilege(String id, Trole trole, Tprivilege tprivilege) {
		this.id = id;
		this.trole = trole;
		this.tprivilege = tprivilege;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Trole getTrole() {
		return this.trole;
	}

	public void setTrole(Trole trole) {
		this.trole = trole;
	}

	public Tprivilege getTprivilege() {
		return this.tprivilege;
	}

	public void setTprivilege(Tprivilege tprivilege) {
		this.tprivilege = tprivilege;
	}

}
