package com.weixin.web.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
// Generated 2014-6-27 15:52:44 by Hibernate Tools 3.2.2.GA

/**
 * TuserRole generated by hbm2java
 */
@Entity
@Table(name = "tuser_role")
public class TuserRole implements java.io.Serializable {

	@Id
	@Column(name = "ID", nullable = false, length = 36)
	private String id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name="ROLEID")
	private Trole trole;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name="USERID")
	private Tuser tuser;

	public TuserRole() {
	}

	public TuserRole(String id) {
		this.id = id;
	}

	public TuserRole(String id, Trole trole, Tuser tuser) {
		this.id = id;
		this.trole = trole;
		this.tuser = tuser;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Trole getTrole() {
		return this.trole;
	}

	public void setTrole(Trole trole) {
		this.trole = trole;
	}

	public Tuser getTuser() {
		return this.tuser;
	}

	public void setTuser(Tuser tuser) {
		this.tuser = tuser;
	}

}
