package com.weixin.web.entity;

// Generated 2014-7-31 10:55:21 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * WxAccountinfo generated by hbm2java
 */
@Entity
@Table(name = "wx_accountinfo")
public class WxAccountinfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "ID", nullable = false, length = 36)
	private String id;
	
	@Column(name = "USERNAME")
	private String username;
	
	@Column(name = "PASSWORD")
	private String password;
	
	@Column(name = "EMAIL")
	private String email;
	
	@Column(name = "PHONE")
	private String phone;
	
	@Column(name = "REGISTTIME")
	private String registTime;
	
	@OneToOne(fetch = FetchType.EAGER, mappedBy = "wxAccountinfo", targetEntity = WxAccount.class)
	private WxAccount wxAccounts;

	public WxAccountinfo() {
	}

	public WxAccountinfo(String id) {
		this.id = id;
	}

	public WxAccountinfo(String id, String username, String password,
			String email, String phone, String registTime, WxAccount wxAccounts) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.email = email;
		this.phone = phone;
		this.registTime = registTime;
		this.wxAccounts = wxAccounts;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getRegistTime() {
		return this.registTime;
	}

	public void setRegistTime(String registTime) {
		this.registTime = registTime;
	}

	public WxAccount getWxAccounts() {
		return this.wxAccounts;
	}

	public void setWxAccounts(WxAccount wxAccounts) {
		this.wxAccounts = wxAccounts;
	}

}
