package com.weixin.web.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WxMenu generated by hbm2java
 */
@Entity
@Table(name = "wx_menu")
public class WXmenu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID", nullable = false, length = 36)
	private String id;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pid")
	private WXmenu wxMenu;
	
	@Column(name = "NAME")
	private String name;
	
	@Column(name = "TYPE")
	private String type;
	
	@Column(name = "MENUKEY")
	private String menuKey;
	
	@Column(name = "MENUTYPE")
	private Integer menuType;
	
	@Column(name = "KEYWORD")
	private String keyWord;
	
	@Column(name = "WEBSITE")
	private String website;
	
	@Column(name = "URL")
	private String url;
	
	@Column(name = "ORDERS")
	private Integer orders;
	
	@Column(name = "ACCOUNTID")
	private String accountId;
	
	@Column(name = "CREATETIME")
	private String createTime;
	
	@Column(name = "MODIFYTIME")
	private String modifyTime;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wxMenu", targetEntity = WXmenu.class)
	private Set wxMenus = new HashSet(0);

	public WXmenu() {
	}

	public WXmenu(String id) {
		this.id = id;
	}

	public WXmenu(String id, WXmenu wxMenu, String name, String type,
			String menuKey, Integer menuType, String keyWord, String website, String url, Integer orders, String accountId,
			String createTime, String modifyTime, Set wxMenus) {
		this.id = id;
		this.wxMenu = wxMenu;
		this.name = name;
		this.type = type;
		this.menuKey = menuKey;
		this.menuType = menuType;
		this.keyWord = keyWord;
		this.website = website;
		this.url = url;
		this.orders = orders;
		this.accountId = accountId;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.wxMenus = wxMenus;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public WXmenu getWxMenu() {
		return this.wxMenu;
	}

	public void setWxMenu(WXmenu wxMenu) {
		this.wxMenu = wxMenu;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getMenuKey() {
		return this.menuKey;
	}

	public void setMenuKey(String menuKey) {
		this.menuKey = menuKey;
	}

	public String getKeyWord() {
		return keyWord;
	}

	public void setKeyWord(String keyWord) {
		this.keyWord = keyWord;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getOrders() {
		return this.orders;
	}

	public void setOrders(Integer orders) {
		this.orders = orders;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Set getWxMenus() {
		return this.wxMenus;
	}

	public void setWxMenus(Set wxMenus) {
		this.wxMenus = wxMenus;
	}

	public Integer getMenuType() {
		return menuType;
	}

	public void setMenuType(Integer menuType) {
		this.menuType = menuType;
	}

	public String getWebsite() {
		return website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	
}
