package com.weixin.web.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2014-8-11 17:30:14 by Hibernate Tools 3.2.2.GA

/**
 * WxQrcode generated by hbm2java
 */
@Entity
@Table(name = "wx_qrcode")
public class WxQrcode implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "ID", nullable = false, length = 36)
	private String id;
	
	@Column(name = "accountId")
	private String accountId;
	
	@Column(name = "createTime")
	private String createTime;
	
	@Column(name = "params")
	private String params;
	
	@Column(name = "scence_id")
	private Integer scenceId;
	
	@Column(name = "action_name")
	private String actionName;
	
	@Column(name = "ticket")
	private String ticket;
	
	@Column(name = "url")
	private String url;

	public WxQrcode() {
	}

	public WxQrcode(String id) {
		this.id = id;
	}

	public WxQrcode(String id, String accountId, String createTime,
			String params, Integer scenceId, String actionName, String ticket, String url) {
		this.id = id;
		this.accountId = accountId;
		this.createTime = createTime;
		this.params = params;
		this.scenceId = scenceId;
		this.actionName = actionName;
		this.ticket = ticket;
		this.url = url;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getParams() {
		return this.params;
	}

	public void setParams(String params) {
		this.params = params;
	}

	public Integer getScenceId() {
		return this.scenceId;
	}

	public void setScenceId(Integer scenceId) {
		this.scenceId = scenceId;
	}

	public String getActionName() {
		return this.actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	public String getTicket() {
		return this.ticket;
	}

	public void setTicket(String ticket) {
		this.ticket = ticket;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	
}
